### ISSUE TITLE
Add skip pool

### ISSUE THREAD

**Issue by jdrowell** [tnyim/jungletv#49]
Add a Skip button that, when clicked by 10% of the active viewers, skips the current video. There's already similar functions in multiplayer games, like in Minecraft a certain percentage of users can sleep at night to make the game skip to the next morning. Presumably only bad (mmmkay) and/or offensive videos would end up being skipped.

**Comment by WilliamsPaulM** [comment]
I think that for each video playing there should be a skip pot:

- If enough user's pay into the pot to equal the skip rate then it should skip and distribute the BAN
- If the pot doesn't match the skip rate by the end of the video then it should distribute the BAN

**Comment by gbl08ma** [comment]
My fault for not opening an issue to track it, but the way video skipping will be implemented has already been decided and indeed it will work using a "skip pool" that will work pretty much like @WilliamsPaulM described.
There will be a "Skip & Tip" tab that will display three addresses where users can send banano:

- One address for the skip pool, once the balance on this pool exceeds a certain threshold the video is skipped. The UI will show the balance and how much is left until the threshold is reached. The economics of how much that threshold should be for each video are yet to be decided, but it is expected that the threshold will always be equal or higher than the cost of skipping through the current means (by enqueuing a new video and paying enough to make it skip).
- One address for the "appreciation pool", which merely serves to let users increase the rewards for the video
- The address of the video requester (which is already displayed in the queue and can currently be copied by clicking on it), this is mostly to make it more prominent in order to encourage rewarding users for requesting good videos.

Sending money to the first two pools increases the total reward for the currently playing video.

This feature, along with other queue quality of life improvements (such as showing chat nicknames in queue where applicable), are blocked by #32. I don't want to introduce any new queue-related features before that is done.
