### ISSUE TITLE
use Piped instead of youtube for embeds

### ISSUE THREAD

**Issue by jameslounds** [tnyim/jungletv#70]
From what I can tell from [Piped’s](https;//piped.video) documentation, this should be as simple as replacing “youtube .com” with “piped.video”  (probably behind an option in settings).

Piped is to YouTube what Nitter is to Twitter. It preserves user privacy, and takes some control out the hands of Google. 

All the same videos are available through Piped, (plus extras from LBRY) and best of all, it will automatically bypass region restrictions, which imo is pretty massive for JTV.

[Docs](https://docs.piped.video/)

**Comment by gbl08ma** [comment]
Piped does not appear to provide any sort of embed, much less one with an embed API for controlling the player that is equivalent to [YouTube's](https://developers.google.com/youtube/iframe_api_reference).
I am also unsure if the official Piped instance would be happy with the bandwidth/resource usage of 400-500 users fetching the same videos in sync with each other, 24 hours a day, through Piped's servers. (Consider that this would basically count as automated activity rather than human-initiated.)
Finally, Piped is probably in violation of the YouTube terms and it is in our best interest to not pile on any potential violations of these terms, as JungleTV must use the YouTube API to obtain video details when enqueuing.

**Comment by NullPlane** [comment]
> From what I can tell from [Piped’s](https;//piped.video) documentation, this should be as simple as replacing “youtube .com” with “piped.video” (probably behind an option in settings).
> 
> Piped is to YouTube what Nitter is to Twitter. It preserves user privacy, and takes some control out the hands of Google.
> 
> All the same videos are available through Piped, (plus extras from LBRY) and best of all, it will automatically bypass region restrictions, which imo is pretty massive for JTV.
> 
> [Docs](https://docs.piped.video/)


@jameslounds accidentally found this question. If it's only for your local browsing experience, you can use [LibRedirect](https://github.com/libredirect/browser_extension) to watch any embeds in the browser through Piped.
