### ISSUE TITLE
Dark mode stopped working in Qutebrowser

### ISSUE THREAD

**Issue by jdrowell** [tnyim/jungletv#75]
Since about a month ago, the light/dark switch does nothing in Qutebrowser (https://qutebrowser.org/). It does work fine in "regular" browsers, like Firefox and Chromium. I tried to look at the JS but it just shows as a veeeery long line in developer tools, even with the pretty printing on. Any idea how to debug this? The following CSS does not show as applied in Qutebrowser (does show in Firefox):

:is(.dark .dark\:text-white)

**Comment by gbl08ma** [comment]
Hello, this likely coincided with the migration from Tailwind CSS v2 to v3. The latest versions of Tailwind CSS implement dark mode in a different way, specifically, the rules for dark mode classes use the `:is()` pseudo-class, as explained [here](https://github.com/tailwindlabs/tailwindcss/pull/10766) (and as you have basically figured out). Older browser engines may not support these properly. Because this is a web standards compatibility problem and JungleTV strictly aims to support the latest version of Firefox, Blink (as used in Chromium) and iOS Safari, there is nothing for us to do here.

**Comment by jdrowell** [comment]
I understand. Just in case people search for this in the future, if you run Qutebrowser with Qt6, it works fine. Unfortunately that's not how it is packaged in Alpine Linux right now. So use Arch Linux or another distro that currently packages it with Qt6.
